<footer>
    <div class="Footer-Container">
        <div class="Footer-Social">
            <a href="https://www.facebook.com/profile.php?id=100010594336098" aria-label="Facebook"><i class="fa-brands fa-facebook"></i></a>
            <a href="https://github.com/ngtrungg" aria-label="Instagram"><i class="fa-brands fa-github"></i></a>
            <a href="https://www.instagram.com/_.nghtrung/" aria-label="Twiiter"><i class="fa-brands fa-instagram"></i></a>
            <a href="https://www.youtube.com/channel/UCMtocow1FhB8wIwhf-7Wx6w" aria-label="Youtube"><i class="fa-brands fa-youtube"></i></a>
        </div>
        <div class="Footer-Nav">
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="jobs.php">Career</a></li>
                <li><a href="apply.php">Apply</a></li>
                <li><a href="about.php">About Us</a></li>
                <li><a href="phpenhancements.php">Enhancement</a></li>
            </ul>
        </div>    
    </div>
    <div class="Footer-Text">
        <p>Copyright &copy;2024</p>
    </div>
</footer>